/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.slu.swingdroid.ui;

import edu.slu.swingdroid.Requirement;
import edu.slu.swingdroid.Requirements;
import edu.slu.swingdroid.Subject;
import edu.slu.swingdroid.Subjects;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 * @author Magsombol, Christine Mary S.
 * @author Conje, Noryza Rose A.
 * @author Espiritu, Christopher
 */
public class AddRequirementUI extends javax.swing.JFrame {

    private Requirements myInstance = Requirements.getInstance();
    private Requirement temporaryRequirement = new Requirement("temporary",
            null, edu.slu.swingdroid.Type.EXAM, null); // Note: Later 
    private JFrame parent;
    private DefaultTableModel model;
    private Requirement requirement;
    private boolean editMode;

    /**
     * Creates new form AddRequirementUI
     *
     * @param parent
     */
    public AddRequirementUI(JFrame parent) {
        UIUtilities.setIconImage(this);
        this.parent = parent;
        parent.setVisible(false);
        editMode = false;
        initComponents();
        dateChooser.getDateEditor().setEnabled(false);
        setTypes(); // Set types combo box
        setSubjects(); // Set available subjects for subjects combo box
        model = (DefaultTableModel) table.getModel();

    }

    /* Helper method for Constructor */
    private void setTypes() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) type.getModel();
        model.addElement(edu.slu.swingdroid.Type.ACTIVITY);
        model.addElement(edu.slu.swingdroid.Type.ASSIGNMENT);
        model.addElement(edu.slu.swingdroid.Type.EXAM);
        model.addElement(edu.slu.swingdroid.Type.MEETING);
        model.addElement(edu.slu.swingdroid.Type.PROJECT);
        model.addElement(edu.slu.swingdroid.Type.QUIZ);
    }

    /* Helper method for Constructor */
    private void setSubjects() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) subjectNames.getModel();
        List<Subject> availableSubjects = Subjects.getInstance().getSubjects();
        for (Subject availableSubject : availableSubjects) {
            model.addElement(availableSubject.getSubjectName());
        }
    }

    /* Helper method for determining the type of a given String */
    private static edu.slu.swingdroid.Type determineType(String determine) {
        switch (determine) {
            case "PROJECT":
                return edu.slu.swingdroid.Type.PROJECT;
            case "ACTIVITY":
                return edu.slu.swingdroid.Type.ACTIVITY;
            case "QUIZ":
                return edu.slu.swingdroid.Type.QUIZ;
            case "ASSIGNMENT":
                return edu.slu.swingdroid.Type.ASSIGNMENT;
            case "MEETING":
                return edu.slu.swingdroid.Type.MEETING;
            case "EXAM":
                return edu.slu.swingdroid.Type.EXAM;
            default:
                throw new RuntimeException("Type invalid!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        leftPane = new javax.swing.JPanel();
        description = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        scroll = new javax.swing.JScrollPane();
        descriptionBox = new javax.swing.JTextArea();
        dueDate = new javax.swing.JLabel();
        subjectNames = new javax.swing.JComboBox();
        dateChooser = new com.toedter.calendar.JDateChooser();
        subject = new javax.swing.JLabel();
        requirementType = new javax.swing.JLabel();
        Pending = new javax.swing.JCheckBox();
        rightPane = new javax.swing.JPanel();
        scroller = new javax.swing.JScrollPane();
        table = new org.jdesktop.swingx.JXTable();
        addAttachmentBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        wrapper.setBackground(new java.awt.Color(229, 255, 204));
        wrapper.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Requirement"));

        leftPane.setBackground(new java.awt.Color(255, 255, 204));
        leftPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        description.setText("Description");

        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        descriptionBox.setBackground(new java.awt.Color(255, 255, 230));
        descriptionBox.setColumns(20);
        descriptionBox.setLineWrap(true);
        descriptionBox.setRows(5);
        descriptionBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                descriptionBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        scroll.setViewportView(descriptionBox);

        dueDate.setText("Due Date");

        subjectNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectNamesActionPerformed(evt);
            }
        });

        subject.setText("Subject");

        requirementType.setText("Type");

        Pending.setBackground(new java.awt.Color(255, 255, 204));
        Pending.setSelected(true);
        Pending.setText("Pending");
        Pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPaneLayout = new javax.swing.GroupLayout(leftPane);
        leftPane.setLayout(leftPaneLayout);
        leftPaneLayout.setHorizontalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPaneLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(description)
                            .addComponent(subject))
                        .addGap(18, 18, 18)
                        .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectNames, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scroll)))
                    .addGroup(leftPaneLayout.createSequentialGroup()
                        .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requirementType)
                            .addComponent(dueDate))
                        .addGap(33, 33, 33)
                        .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pending))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftPaneLayout.setVerticalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subjectNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject))
                .addGap(18, 18, 18)
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPaneLayout.createSequentialGroup()
                        .addComponent(description)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requirementType))
                .addGap(18, 18, 18)
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDate))
                .addGap(18, 18, 18)
                .addComponent(Pending)
                .addGap(25, 25, 25))
        );

        rightPane.setBackground(new java.awt.Color(255, 255, 204));
        rightPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Attachments"));
        rightPane.setMinimumSize(new java.awt.Dimension(401, 272));

        table.setBackground(new java.awt.Color(255, 255, 230));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attachments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroller.setViewportView(table);

        addAttachmentBtn.setBackground(new java.awt.Color(205, 229, 255));
        addAttachmentBtn.setText("Add Attachment");
        addAttachmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttachmentBtnActionPerformed(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(205, 229, 255));
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPaneLayout = new javax.swing.GroupLayout(rightPane);
        rightPane.setLayout(rightPaneLayout);
        rightPaneLayout.setHorizontalGroup(
            rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPaneLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(addAttachmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(49, 49, 49))
            .addGroup(rightPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroller)
                .addContainerGap())
        );
        rightPaneLayout.setVerticalGroup(
            rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroller, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addAttachmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        saveBtn.setBackground(new java.awt.Color(205, 229, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(205, 229, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(153, 153, 153)
                .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77))
            .addGroup(wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(wrapper);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subjectNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectNamesActionPerformed

    }//GEN-LAST:event_subjectNamesActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            if (dateChooser.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Please choose a due date", "Error",
                        JOptionPane.ERROR_MESSAGE);
                throw new RuntimeException("Date cannot be null...");
            } else { // We add the requirement
                temporaryRequirement.setActive(Pending.isSelected());
                temporaryRequirement.setDescription(descriptionBox.getText());
                temporaryRequirement.setDueDate(dateChooser.getCalendar());
                temporaryRequirement.setType(determineType(type.getSelectedItem().toString()));
                temporaryRequirement.setSubject(new Subject(subjectNames.getSelectedItem().toString()));
                addAttachments(temporaryRequirement);
                Requirements.getInstance().addRequirement(temporaryRequirement);

                this.dispose();
                HomeUserInterface homeUI = (HomeUserInterface) parent;
                homeUI.syncTable();
                parent.setVisible(true);
            }
        } catch (RuntimeException e) {
            System.err.println(e);
        } catch (Exception e) {
            System.err.println(e);
        }

//        parent.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_saveBtnActionPerformed
    private void addAttachments(Requirement requirement) {
        try {
            File filesDirectory = new File("files");
            if (!filesDirectory.exists()) {
                filesDirectory.mkdir();
            }
            Vector vector = model.getDataVector();
            for (Object object : vector) {
                Vector current = (Vector) object;
                File converted = (File) current.get(0);
                try {
                    File toStore = new File(filesDirectory, "" + converted.getName());
                    Files.copy(converted.toPath(), toStore.toPath());
                    requirement.addAttachment(new File(converted.getName()));
                } catch (FileAlreadyExistsException ex) {
                    JOptionPane.showMessageDialog(this, "Duplicate file entry, please"
                            + " rename the file...", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (IOException ex) {
                    System.err.println(ex);
                }
            }
        } catch (NullPointerException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "No attachments were added...", "Inform", JOptionPane.INFORMATION_MESSAGE);
            parent.setVisible(true);
            this.dispose();
        }
    }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        /* If there are attachments delete them first before closing this JFrame*/
        if (temporaryRequirement.getAttachments() != null
                && !temporaryRequirement.getAttachments().isEmpty()) {
            File filesDirectory = new File("files");
            if (!filesDirectory.exists()) {
                filesDirectory.mkdir();
            }
            File toDelete;
            for (File row : temporaryRequirement.getAttachments()) {
                try {
                    toDelete = new File(filesDirectory, row.getName());
                    Files.deleteIfExists(toDelete.toPath());
                } catch (IOException ex) {
                    System.err.println(ex);
                }
            }

        }
        /* If there are no attachments dispose immediately */
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void descriptionBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_descriptionBoxAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionBoxAncestorAdded

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void addAttachmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttachmentBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        File selected = fileChooser.getSelectedFile();
        model = (DefaultTableModel) table.getModel();
        for (Object row : model.getDataVector()) {
            Vector current = (Vector) row;
            File file = (File) current.get(0);
            if (file.getAbsolutePath().equalsIgnoreCase(selected.getAbsolutePath())) {
                JOptionPane.showMessageDialog(this, "Duplicate file entry, please"
                        + " rename the file...", "Error", JOptionPane.ERROR_MESSAGE);
                throw new RuntimeException("Duplicate file entry...");
            }

        }
        // if(selected.getName())
        //        Files.exists(null, Link);
        File filesDirectory = new File("files");
        if (!filesDirectory.exists()) {
            filesDirectory.mkdir();
        }
        List<File> filesInside = new ArrayList<>(Arrays.asList(filesDirectory.listFiles()));
        if (filesInside.contains(new File(filesDirectory, selected.getName()))) {
            JOptionPane.showMessageDialog(this, "Duplicate file entry, please"
                    + " rename the file...", "Error", JOptionPane.ERROR_MESSAGE);
            throw new RuntimeException("Duplicate file entry...");
        } else {
            model = (DefaultTableModel) table.getModel();
            model.addRow(new Object[]{selected.getAbsoluteFile()});
        }
    }//GEN-LAST:event_addAttachmentBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        try {
            //editMode = requirement.getAttachments().isEmpty()? true : false;
            model = (DefaultTableModel) table.getModel();
            if (editMode) {
                File filesDirectory = new File("files");
                if (!filesDirectory.exists()) {
                    filesDirectory.mkdir();
                }
                File tableValue = (File) table.getValueAt(table.getSelectedRow(), 0);
                System.out.println(tableValue.getAbsoluteFile());
                File toDelete = new File(filesDirectory, tableValue.getName());
                System.out.println(toDelete);
                try {
                    requirement.removeAttachment(table.getSelectedRow());
                    Files.deleteIfExists(toDelete.toPath());
                    System.out.println(table.getSelectedRow());
                    model.removeRow(table.getSelectedRow());
                    System.out.println(requirement.getAttachments().toString());
                } catch (IOException ex) {
                    System.err.println(ex);
                }
            } else {
                model.removeRow(table.getSelectedRow());
            }

        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Please select the row to remove...", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRequirementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddRequirementUI(new JFrame()).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Pending;
    private javax.swing.JButton addAttachmentBtn;
    private javax.swing.JButton cancelBtn;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel description;
    private javax.swing.JTextArea descriptionBox;
    private javax.swing.JLabel dueDate;
    private javax.swing.JPanel leftPane;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel requirementType;
    private javax.swing.JPanel rightPane;
    private javax.swing.JButton saveBtn;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JScrollPane scroller;
    private javax.swing.JLabel subject;
    private javax.swing.JComboBox subjectNames;
    private org.jdesktop.swingx.JXTable table;
    private javax.swing.JComboBox type;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
