/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.slu.swingdroid.ui;

import edu.slu.swingdroid.Requirement;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chris
 */
public class AttachmentsUI extends javax.swing.JFrame {

    private DefaultTableModel model;
    private Requirement requirement;
    private JFrame parent;
    private boolean editMode;
    /**
     * Creates new form AttachmentsUI
     * @param requirementId
     */
    public AttachmentsUI(Requirement requirement, JFrame parent, boolean editMode) {
        initComponents(); // NOTE: Missing 
        this.requirement = requirement;
        this.parent = parent;
        this.parent.setVisible(false);
        this.editMode = editMode;
        if(requirement.getAttachments() != null &&
                !requirement.getAttachments().isEmpty())
            initializeAttachments(requirement.getAttachments());

    }
    
    private void initializeAttachments(List<File> attachments){
        DefaultTableModel tableModel = (DefaultTableModel)table.getModel();
        tableModel.setRowCount(0);
        for (File attachment : attachments) {
            tableModel.addRow(new Object[]{attachment.getAbsoluteFile()});
        }
        table.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        scroller = new javax.swing.JScrollPane();
        table = new org.jdesktop.swingx.JXTable();
        doneBtn = new javax.swing.JButton();
        addAttachmentBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attachments");
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        wrapper.setBackground(new java.awt.Color(229, 255, 204));
        wrapper.setMinimumSize(new java.awt.Dimension(401, 272));
        wrapper.setName("wrapper"); // NOI18N

        scroller.setName("scroller"); // NOI18N

        table.setBackground(new java.awt.Color(255, 255, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attachments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setName("table"); // NOI18N
        scroller.setViewportView(table);

        doneBtn.setText("Done");
        doneBtn.setName("doneBtn"); // NOI18N
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        addAttachmentBtn.setText("Add Attachment");
        addAttachmentBtn.setName("addAttachmentBtn"); // NOI18N
        addAttachmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttachmentBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.setName("removeBtn"); // NOI18N
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapperLayout.createSequentialGroup()
                        .addComponent(scroller)
                        .addContainerGap())
                    .addGroup(wrapperLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(doneBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(addAttachmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scroller, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAttachmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(wrapper);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addAttachmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttachmentBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        File selected = fileChooser.getSelectedFile();
        // if(selected.getName())
//        Files.exists(null, Link);
        File filesDirectory = new File("files");
        if (!filesDirectory.exists()) {
            filesDirectory.mkdir();
        }
        List<File> filesInside = new ArrayList<>(Arrays.asList(filesDirectory.listFiles()));
        if (filesInside.contains(new File(filesDirectory, selected.getName()))) {
            JOptionPane.showMessageDialog(this, "Duplicate file entry, please"
                    + " rename the file...", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            model = (DefaultTableModel) table.getModel();
            model.addRow(new Object[]{selected.getAbsoluteFile()});
        }

    }//GEN-LAST:event_addAttachmentBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
      // Files.copy
        //  Object value = jXTable1.getValueAt(jXTable1.getSelectedColumn(), 0);
        //   File selectedFile = (File) value;
        //  System.out.println(selectedFile.getAbsoluteFile());
        try {
            File filesDirectory = new File("files");
            if (!filesDirectory.exists()) {
                filesDirectory.mkdir();
            }
            Vector vector = model.getDataVector();
            for (Object object : vector) {
                Vector current = (Vector) object;
                File converted = (File) current.get(0);
                try {
                    File toStore = new File(filesDirectory, "" + converted.getName());
                    Files.copy(converted.toPath(), toStore.toPath());
                    requirement.addAttachment(new File(converted.getName()));
                } catch (FileAlreadyExistsException ex) {
                    JOptionPane.showMessageDialog(this, "Duplicate file entry, please"
                            + " rename the file...", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (IOException ex) {
                    System.err.println(ex);
                }
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "No attachments were added..."
                    , "Inform", JOptionPane.INFORMATION_MESSAGE);
            parent.setVisible(true);
            this.dispose();
        }

        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doneBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        try {
            //editMode = requirement.getAttachments().isEmpty()? true : false;
            model = (DefaultTableModel) table.getModel();
            if (editMode) {
            File filesDirectory = new File("files");
            if (!filesDirectory.exists()) {
                filesDirectory.mkdir();
            }
            File tableValue = (File)table.getValueAt(table.getSelectedRow(), 0);
                System.out.println(tableValue.getAbsoluteFile());
            File toDelete = new File(filesDirectory, tableValue.getName());
                System.out.println(toDelete);
                try {
                    requirement.removeAttachment(table.getSelectedRow());
                    Files.deleteIfExists(toDelete.toPath());
                    System.out.println(table.getSelectedRow());
                    model.removeRow(table.getSelectedRow());                    
                    System.out.println(requirement.getAttachments().toString());
                } catch (IOException ex) {
                    System.err.println(ex);
                }
            }else{
            model.removeRow(table.getSelectedRow());
            }
            
        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Please select the row to remove...", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttachmentsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttachmentsUI(null, null, false).setVisible(true); // NOTE for testing purposes
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAttachmentBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton doneBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JScrollPane scroller;
    private org.jdesktop.swingx.JXTable table;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
