/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.slu.swingdroid.ui;

import edu.slu.swingdroid.Requirement;
import edu.slu.swingdroid.Requirements;
import edu.slu.swingdroid.Subject;
import edu.slu.swingdroid.Type;
import edu.slu.swingdroid.db.RequirementsManager;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Noryza
 */
public class PopUpUI extends javax.swing.JPanel {

    /**
     * Creates new form PopUpUI
     */
    public PopUpUI() {
        initComponents();
        getRow();
    }
    
    private static void getRow() {
        HashMap<Integer, Requirement> req = RequirementsManager.getAllRows();
        for (Map.Entry<Integer, Requirement> entrySet : req.entrySet()) {
            Integer key = entrySet.getKey();
            Requirement value = entrySet.getValue();
            System.out.println(value);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        popUpTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(229, 255, 204));

        popUpTextArea.setBackground(new java.awt.Color(255, 255, 204));
        popUpTextArea.setColumns(20);
        popUpTextArea.setRows(5);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, popUpTextArea, org.jdesktop.beansbinding.ObjectProperty.create(), popUpTextArea, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        popUpTextArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                popUpTextAreaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(popUpTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void popUpTextAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_popUpTextAreaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_popUpTextAreaAncestorAdded
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PopUpUI().setVisible(true);
            }
        });       
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea popUpTextArea;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
